[package]
name = "ver-from-git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
git2 = "0.16.0"
semver = "1.0.16"
