[build]
rustc-wrapper = "sccache"
# Disabled for now - conflicts with some git submodule dependencies
# rustflags = "--deny warnings"
# known to conflict with sccache
incremental = false

[env]
CARGO_CACHE_RUSTC_INFO = "1"

[net]
git-fetch-with-cli = true
