[package]
name = "gen-source-files-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
pathdiff = "0.2.1"
walkdir = "2.3.2"
